### ISSUE TITLE
File packed with UPX crash and does not start

### ISSUE THREAD

**Issue by Mrgaton** [hasherezade/pe_to_shellcode#33]
I tried to convert files packed with upx to reduce shellcode size but doesn't just not work but increases shell code size than normal file to shell code link to upx : https://github.com/upx/upx

**Comment by Mrgaton** [comment]
By the way, very good work, @hasherezade , you saved my life with this project.

**Comment by hasherezade** [comment]
hi @Mrgaton ! thanks for reporting, I will check it soon

**Comment by hasherezade** [comment]
@Mrgaton - I checked it but I wasn't able to reproduce the crash. Can you please send me the file that was crashing to my e-mail: hasherezade-at-protonmail.com?

The increased shellcode size may come from the fact that during the shellcodification PE is converted to the virtual format, so that it can be loaded in-place, without allocating additional memory. It is also allow the shellcodes to be injected in the processes with DCP (dynamic code prohibited) enabled. More details described in this thread: https://github.com/hasherezade/pe_to_shellcode/issues/19 . Files that are packed, are normally smaller on disk, but they expand significantly in memory. And during the conversion, the size for all expanded content is reserved.

One issue that I observed with UPX, is that, sometimes during the compression UPX removes relocation table. And the pe2shc is set not to proceed if the file has no relocations. So you may see a message like this:

![no_reloc](https://user-images.githubusercontent.com/3115348/222970299-241206a7-60ea-43bd-8932-e5eb10c2c545.png)

But in cases where UPX leaves relocation table, I had no problems converting and then running the converted versions.
Those are my testcases. It is [LoadOrd from Sysinternals](https://learn.microsoft.com/en-us/sysinternals/downloads/loadorder), in 32 and 64 bit version, packed with the [UPX v4.0.2](https://github.com/upx/upx/releases/tag/v4.0.2):

The generated shellcodes: 
[LoadOrd_upx.shc.zip](https://github.com/hasherezade/pe_to_shellcode/files/10892196/LoadOrd_upx.shc.zip)

![test32b](https://user-images.githubusercontent.com/3115348/222970700-18a234dd-385d-46d4-a601-75c3b675cc15.png)

![test2](https://user-images.githubusercontent.com/3115348/222970704-a51fa5d3-e011-4f4a-80de-9bd5df7226d6.png)

So, in order to be able help your case, I would need to see your file and investigate deeper what exactly went wrong.

**Comment by Mrgaton** [comment]
i was using the option --best on a dll but ill try again

**Comment by hasherezade** [comment]
@Mrgaton - I tried with the option `--best` too, and still could not reproduce the crash. All my converted samples worked.

**Comment by Mrgaton** [comment]
Maibye was upx fault or my program fault sorry ill do some more test

**Comment by hasherezade** [comment]
ok, please double-check and let me know

**Comment by hasherezade** [comment]
no probs, I am glad that it got solved
