### ISSUE TITLE
Applications with TLS callbacks are not supported!

### ISSUE THREAD

**Issue by xuxuedong** [hasherezade/pe_to_shellcode#6]
when i attemp to convert a 64 bit pe file, it has above error...

**Comment by hasherezade** [comment]
It is true, they are not supported. It's not a bug. It is just an inevitable limitation that not all PE files are suitable to be converted.

**Comment by xuxuedong** [comment]
thanks a lot, but can i get rid of the "tls callback" of a pe file to use this tool? such as recompile it?

**Comment by hasherezade** [comment]
please check the latest release, it has some improvements about it: https://github.com/hasherezade/pe_to_shellcode/releases/tag/v0.8

**Comment by ntrischi** [comment]
Will TLS callbacks ever be supported? Is this something out of scope of this project?

**Comment by hasherezade** [comment]
> Will TLS callbacks ever be supported? Is this something out of scope of this project?

The objective of this project was to replicate the functionality of the classic [Reflective DLL injection](https://github.com/stephenfewer/ReflectiveDLLInjection) - and it doesn't support TLS callbacks either. So after having the equivalent functionality covered, I was not planning to go further in this project. But if more people will need TLS callbacks, I will consider adding them. At this moment I am just not sure if it pays off, because more important for me was keeping the stub small and simple.

**Comment by hasherezade** [comment]
hi! if you are still interested, I added TLS callbacks support in the latest release:
https://github.com/hasherezade/pe_to_shellcode/releases/tag/v1.0
